stages:
  - NodeAuditApiServer
  - NodeAuditWebSite


cache:
  paths:
    - /api_server/node_modules/
    - /web_site/node_modules/


node_audit1:
  stage: NodeAuditApiServer
  image: node:alpine
  before_script:
    - cd api_server
    - npm install
  script:
    - npm audit
  allow_failure: false


  node_audit2:
  stage: NodeAuditWebSite
  image: node:alpine
  before_script:
    - cd web_site
    - npm install
  script:
    - npm audit
  allow_failure: false