version: "3.9"


networks:
  database_amour_connect:
      external: true

services:

  frontend-amourconnect:
    build:
      context: .
      dockerfile: Dockerfile.node_frontend
    ports:
      - "3000:3000"
    networks:
      - database_amour_connect