networks:
  database_amour_connect:
      external: true

services:

  frontamourconnect:
    container_name: frontamourconnect
    restart: on-failure:5
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.node_frontend
      args:
        - NEXT_PUBLIC_PORT=${NEXT_PUBLIC_PORT}
        - IP_NOW_FRONTEND=${IP_NOW_FRONTEND}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - ${NEXT_PUBLIC_PORT}:${NEXT_PUBLIC_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontamourconnect.rule=Host(`${IP_NOW_FRONTEND}`)"
      - "traefik.http.routers.frontamourconnect.tls=true"
      - "traefik.http.routers.frontamourconnect.tls.certresolver=prodresolver"
      - "traefik.http.routers.frontamourconnect.entrypoints=websecure"
      - "traefik.http.services.frontamourconnect.loadbalancer.server.port=${NEXT_PUBLIC_PORT}"
    networks:
      - database_amour_connect