version: "3.9"

services:


  frontend-amourconnect:
    build:
      context: .
      dockerfile: Dockerfile.node_frontend
    ports:
      - "5003:${PORT_FRONT_IN_DOCKER}"
    volumes:
      - ./:/app/site/frontend
    command: sh -c "npm install -g npm@latest && npm update && npm update --save-dev && npm install && npm run dev"
    networks:
      - amour_connect-front
    pids_limit: 100
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 10G


networks:
    amour_connect-front: