version: "3.9"


networks:
  amour_connect:
      driver: bridge

services:

  frontend-amourconnect:
    build:
      context: .
      dockerfile: Dockerfile.node_frontend
    ports:
      - "5003:3000"
    volumes:
      - ./:/app/site/frontend
    command: sh -c "npm install -g npm@latest && npm update && npm update --save-dev && npm install && npm run dev"
    networks:
      - amour_connect