networks:
  database_amour_connect:
      external: true

services:

  frontamourconnect:
    container_name: frontamourconnect
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.node_frontend
      args:
        - NEXT_PUBLIC_PORT=${NEXT_PUBLIC_PORT}
        - IP_NOW_FRONTEND=${IP_NOW_FRONTEND}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - ${NEXT_PUBLIC_PORT}:${NEXT_PUBLIC_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontamourconnect.rule=Host(`tubevideo.shop`)"
      - "traefik.http.routers.frontamourconnect.tls=true"
      - "traefik.http.routers.frontamourconnect.tls.certresolver=prodresolver"
      - "traefik.http.routers.frontamourconnect.entrypoints=websecure"
      - "traefik.http.routers.frontamourconnect.service=frontamourconnect"
      - "traefik.http.services.frontamourconnect.loadbalancer.server.port=${NEXT_PUBLIC_PORT}"
      # Configuration for www.tubevideo.shop with redirection
      - "traefik.enable=true"
      - "traefik.http.routers.frontamourconnect-www-redirect.rule=Host(`www.tubevideo.shop`)"
      - "traefik.http.routers.frontamourconnect-www-redirect.tls=true"
      - "traefik.http.routers.frontamourconnect-www-redirect.tls.certresolver=prodresolver"
      - "traefik.http.routers.frontamourconnect-www-redirect.entrypoints=websecure"
      - "traefik.http.routers.frontamourconnect-www-redirect.middlewares=frontamourconnect-www-redirect@docker"
      # Redirection middleware
      - "traefik.http.middlewares.frontamourconnect-www-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.frontamourconnect-www-redirect.redirectregex.regex=^https?://www\\.(.*)"
      - "traefik.http.middlewares.frontamourconnect-www-redirect.redirectregex.replacement=https://$$1"
       #Define midleware 
      - "traefik.http.routers.frontamourconnect.middlewares=crowdsec-frontamourconnect@docker" 
      ## Middleware configuration
      - "traefik.http.middlewares.crowdsec-frontamourconnect.plugin.crowdsec-bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec-frontamourconnect.plugin.crowdsec-bouncer.crowdseclapikey=${CrowdSec_BOUNCER_API_KEY}"
    networks:
      - database_amour_connect