# Dockerfile.node_frontend
FROM node:alpine

ARG NEXT_PUBLIC_PORT
ARG NEXT_PUBLIC_API_URL
ARG IP_NOW_FRONTEND

ENV IP_NOW_FRONTEND=$IP_NOW_FRONTEND
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_PORT=$NEXT_PUBLIC_PORT

WORKDIR /app/site/front/

COPY package.json package-lock.json ./

RUN npm install

COPY . ./

RUN npm run build

CMD ["npm", "start"]