networks:
  amour_connect:
      driver: bridge
  
services:

    postgresdbsqlamourconnect:
        image: postgres:latest
        container_name: postgresdbsqlamourconnect
        restart: unless-stopped
        environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_DATABASE}
        ports:
           - "127.0.0.1:5433:5432"
        volumes:
          - pgdataamourconnect:/var/lib/postgresql/data:rw
        labels:
          - traefik.enable=false
        networks:
          - amour_connect


    pgadminamourconnect:
        image: dpage/pgadmin4:latest
        container_name: pgadminamourconnect
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "127.0.0.1:9089:80"
        depends_on:
            - postgresdbsqlamourconnect
        labels:
            - traefik.enable=false
        networks:
            - amour_connect


    redis-amourconnect:
        image: redis:latest
        container_name: redis-amourconnect
        restart: unless-stopped
        ports:
          - "127.0.0.1:6379:6379"
        volumes:
          - redis-data:/data
        labels:
          - traefik.enable=false
        networks:
          - amour_connect


volumes:
  pgdataamourconnect:
  redis-data: