networks:
  database_amour_connect:
      external: true

services:

  apinetcore:
    container_name: apinetcore
    restart: on-failure:5
    env_file:
      - .env
    ports:
      - ${PORT_BACKEND}:${PORT_BACKEND}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - ASPNETCORE_URLS=http://+:${PORT_BACKEND}
        - ASPNETCORE_ENVIRONMENT=Production
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.apinet.rule=Host(`${IP_NOW_BACKENDAPI}`)
      - traefik.http.routers.apinet.tls=true
      - traefik.http.routers.apinet.tls.certresolver=prodresolver
      - traefik.http.routers.apinet.entrypoints=websecure
     # - traefik.http.services.apinet.loadbalancer.server.port=80
    networks:
        - database_amour_connect