networks:
  database_amour_connect:
      external: true

services:

  apiamourconnect:
    container_name: apiamourconnect
    restart: on-failure:5
    env_file:
      - .env
    ports:
      - ${PORT_BACKEND}:${PORT_BACKEND}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - ASPNETCORE_URLS=http://+:${PORT_BACKEND}
        - ASPNETCORE_ENVIRONMENT=Production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apiamourconnect.rule=Host(`${IP_NOW_BACKENDAPI}`)"
      - "traefik.http.routers.apiamourconnect.tls=true"
      - "traefik.http.routers.apiamourconnect.tls.certresolver=prodresolver"
      - "traefik.http.routers.apiamourconnect.entrypoints=websecure"
      - "traefik.http.services.apiamourconnect.loadbalancer.server.port=80"
    networks:
        - database_amour_connect