version: "3.9"


networks:
  amour_connect:
     driver: bridge


services:

  apinetcore:
    image: docker.io/library/apinetcore
    depends_on:
       - postgres-amourconnect
    container_name: services-api-amourconnect
    ports:
      - "3212:80"
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - ConnectionStrings__DefaultConnection=${DB_USER} ID=${DIALECT_SQL};Password=${DB_PASSWORD};Server=${DB_HOST};Port=${Port_db};Database=${DB_DATABASE};IntegratedSecurity=true;Pooling=true;
        - ASPNETCORE_URLS=http://+80
    networks:
      - amour_connect
  

  postgres-amourconnect:
    image: postgres:latest
    container_name: postgres-amourconnect
    restart: on-failure:5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
       - "127.0.0.1:5433:5432"
    volumes:
      - pgdata-amourconnect:/var/lib/postgresql/data:rw
      - ./Models/user.sql:/docker-entrypoint-initdb.d/user.sql:ro
    networks:
      - amour_connect
    pids_limit: 100
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 10G


  pgadmin-amourconnect:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-amourconnect
    restart: on-failure:5
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "127.0.0.1:9089:80"
    depends_on:
      - postgres-amourconnect
    networks:
      - amour_connect
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G


volumes:
  pgdata-amourconnect: