networks:
  database_amour_connect:
      external: true

services:
  redis-amourconnect:
    image: redis:latest
    container_name: redis-amourconnect
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    labels:
      - traefik.enable=false
    networks:
      - database_amour_connect

volumes:
  redis-data: