name: NodeJS, .NET Core Audit and Docker Push Image

on:
  push:
    branches:
      - main
      - test_before_prod
  pull_request:
    branches:
      - main

jobs:

  audit-lib:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout librairies
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and run audit in Web Site folder
      run: |
        cd web_site
        npm install
        npm audit
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies and run audit in Api Server folder
      run: |
        cd server_api
        dotnet restore
        dotnet list package --vulnerable

  docker-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Docker setup
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: amourconnect
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Create .env file DataBase
        run: |
          touch server_api/DataBase/.env
          echo "${{ secrets.DATABASE_ENV_PROD }}" > server_api/DataBase/.env

      - name: Build image Database
        run: |
          cd server_api/DataBase
          docker-compose -f compose.yaml up -d


      - name: Create .env file WebSite
        run: |
          touch web_site/.env
          echo "${{ secrets.WEBSITE_ENV_PROD }}" > web_site/.env

      - name: Build image Web Site and Push
        run: |
           cd web_site/
           docker-compose -f compose.yaml up -d
           CONTAINER_ID=$(docker ps -q --filter "name=frontend-amourconnect")
           IMAGE_NAME_REPOSITORY=amourconnect/test_prod_amourconnect
           docker container commit $CONTAINER_ID $IMAGE_NAME_REPOSITORY
           docker tag $IMAGE_NAME_REPOSITORY $IMAGE_NAME_REPOSITORY:FrontAmourConnect
           docker push $IMAGE_NAME_REPOSITORY:FrontAmourConnect


      - name: Create .env file Server Api
        run: |
            touch server_api/.env
            echo "${{ secrets.SERVER_ENV_PROD }}" > server_api/.env
      
      - name: Build image Server Api and Push
        run: |
            cd server_api/
            docker-compose -f compose.yaml up -d
            CONTAINER_ID=$(docker ps -q --filter "name=apinetcore")
            IMAGE_NAME_REPOSITORY=amourconnect/test_prod_amourconnect
            docker container commit $CONTAINER_ID $IMAGE_NAME_REPOSITORY
            docker tag $IMAGE_NAME_REPOSITORY $IMAGE_NAME_REPOSITORY:ApiAmourConnect
            docker push $IMAGE_NAME_REPOSITORY:ApiAmourConnect