name: NodeJS, .NET Core Audit and Docker Push Image

on:
  push:
    branches:
      - main
      - test_before_prod
  pull_request:
    branches:
      - main

jobs:

  audit-lib:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout librairies
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and run audit in Web Site folder
      run: |
        cd web_site
        npm install
        npm audit
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies and run audit in Api Server folder
      run: |
        cd server_api
        dotnet restore
        dotnet list package --vulnerable

  docker-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Docker setup
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push web site image
        uses: docker/build-push-action@v5
        with:
          context: web_site
          file: web_site/Dockerfile.node_frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REGISTRY }}:WebSiteFront
          services: web_site_amourconnect
          build-args: |
                NEXT_PUBLIC_API_URL=${{ secrets.IP_NOW_BACKENDAPI }}
                PORT=${{ secrets.PORT_FRONT }}
                IP_FRONT=${{ secrets.IP_NOW_FRONTEND }}