name: NodeJS and .NET Core Audit

on: [push, pull_request]

jobs:
  node-audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies and run audit in Web Site folder
      run: |
        cd web_site
        npm install
        npm audit

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies and run audit in Api Server folder
      run: |
        cd server_api
        dotnet restore
        dotnet list package --vulnerable